spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v4/products

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v4/orders

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v4/inventory

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

#        - id: identity-service
#          uri: lb://identity-service
#          predicates:
#            - Path=/api/v4/auth/**

  application:
    name: api-gateway

server:
  port: 4041

