spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fils1?
    url: jdbc:mysql://localhost:3306/microservices_auth
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: identity-service

server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka